#!/bin/bash
# CROWN Data Server Setup Script
# Run this on your cloud server (43.163.98.133) to serve reservoir CSV data
# via HTTPS with CORS headers for the GitHub Pages website.
#
# Requires: nginx installed, domain pointed to this server's IP
#
# Before running:
# 1. Point your DNS (crown.gzhaowater.com) to 43.163.98.133
# 2. Make sure port 80 and 443 are open in the security group
# 3. Run: sudo apt install nginx certbot python3-certbot-nginx

set -e

DOMAIN="${1:-crown.gzhaowater.com}"
DATA_DIR="/home/ubuntu/CROWN"

echo "=== CROWN Data Server Setup ==="
echo "Domain: $DOMAIN"
echo "Data directory: $DATA_DIR"

if [ ! -d "$DATA_DIR" ]; then
    echo "ERROR: $DATA_DIR does not exist!"
    exit 1
fi

CSV_COUNT=$(ls "$DATA_DIR"/*.csv 2>/dev/null | wc -l)
echo "Found $CSV_COUNT CSV files"

# Install dependencies
echo ""
echo "Installing nginx and certbot..."
sudo apt update -qq
sudo apt install -y -qq nginx certbot python3-certbot-nginx

# Create nginx config
echo ""
echo "Configuring nginx..."

sudo tee /etc/nginx/sites-available/crown-data > /dev/null << EOF
server {
    listen 80;
    server_name $DOMAIN;

    # Let's Encrypt challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirect HTTP to HTTPS
    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl http2;
    server_name $DOMAIN;

    # SSL certificates (will be auto-generated by certbot)
    ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;

    # Data endpoint
    location /data/ {
        alias $DATA_DIR/;
        add_header Access-Control-Allow-Origin * always;
        add_header Access-Control-Allow-Methods 'GET, OPTIONS' always;
        add_header Access-Control-Allow-Headers 'Content-Type' always;
        add_header Cache-Control 'public, max-age=3600' always;
        types {
            text/csv csv;
        }
        autoindex on;
    }

    # Simple index page
    location = /data/ {
        alias $DATA_DIR/;
        add_header Access-Control-Allow-Origin * always;
        default_type text/html;
        return 200 '<html><body><h1>CROWN Data Server</h1><p>$CSV_COUNT reservoir CSV files available</p><p><a href="/data/57.csv">Sample: 57.csv</a></p></body></html>';
    }
}
EOF

sudo ln -sf /etc/nginx/sites-available/crown-data /etc/nginx/sites-enabled/

# Remove default site if it conflicts
sudo rm -f /etc/nginx/sites-enabled/default

sudo nginx -t

# Generate SSL certificate
echo ""
echo "Generating SSL certificate with Let's Encrypt..."
sudo certbot --nginx -d $DOMAIN --non-interactive --agree-tos --register-unsafely-without-email || {
    echo ""
    echo "Certbot failed. Make sure:"
    echo "  1. DNS for $DOMAIN points to $(curl -s ifconfig.me 2>/dev/null || echo 'this server')"
    echo "  2. Port 80 is open in your security group"
    echo ""
    echo "You can retry later with: sudo certbot --nginx -d $DOMAIN"
}

sudo systemctl reload nginx

# Auto-renew SSL
echo ""
echo "Setting up automatic SSL renewal..."
(sudo crontab -l 2>/dev/null | grep -v certbot; echo "0 3 * * * certbot renew --quiet --post-hook 'systemctl reload nginx'") | sudo crontab -

echo ""
echo "=== Setup Complete! ==="
echo ""
echo "Your data is now accessible at:"
echo "  https://$DOMAIN/data/57.csv"
echo ""
echo "Test it:"
echo "  curl https://$DOMAIN/data/57.csv | head -5"
echo ""
echo "Check nginx status:"
echo "  systemctl status nginx"
